#! /usr/bin/python
# -*- coding: utf-8 -*-

#	Copyright (C) 2014  Enno Rodegerdts

#  This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
# 
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
# 
#     You should have received a copy of the GNU General Public License along
#     with this program; if not, write to the Free Software Foundation, Inc.,
#     51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

#import ephem
#import math
from alma_ephem import *




def sunmoontab(date):
    """generates LaTeX table for sun and moon
    """
    tab = r'''\noindent
    \begin{tabular*}{0.2\textwidth}[t]{@{\extracolsep{\fill}}|c|rr|}
    '''
    d = 0
    while d < 3:
        tab = tab + r'''\hline 
        \hline 
        \multicolumn{1}{|c|}{\textbf{%s}} &\multicolumn{1}{c}{\textbf{GHA}} &\multicolumn{1}{c|}{\textbf{Dec}}\\ 
        \hline
        ''' %(ephem.date(date+d).datetime().strftime("%d"))
        da = date+d
        h = 0
        while h < 24:
            eph = sunmoon(da)
            line = "%s & %s & %s \\\ \n" %(h,eph[0],eph[1])
            tab = tab + line
            h += 1
            da = da+ephem.hour
        vd = vdmean(date+d)
        tab = tab + r"""\hline
        & \multicolumn{1}{c}{SD.=%s} & \multicolumn{1}{c|}{d=%s} \\
        \hline
        """ %(vd[1],vd[0])
        d = d + 1
    tab = tab+r"""\end{tabular*}"""
    return tab
    


def page(date):
    """creates a page(15 days) of the Sun almanac
    """
    page = r"""\sffamily
    \noindent
    
    
    
    \begin{flushright}
    \textbf{%s to %s}
    \end{flushright}
    
    \begin{scriptsize}
    """ %(ephem.date(date).datetime().strftime("%Y %B %d"),ephem.date(date+14).datetime().strftime("%b. %d"))
    page = page + sunmoontab(date)
    page = page + sunmoontab(date+3)
    page = page + sunmoontab(date+6)
    page = page + sunmoontab(date+9)
    page = page + sunmoontab(date+12)
    page = page + r"""\end{scriptsize}
    \newpage
    
    
    
    """
    return page
    
    
def pages(date,p):
    """make i pages beginning with date"""
    d = ephem.date(date)
    out = ''
    for i in range(p):
        out = out + page(d)
        d = d +15
    return out
        
def almanac(year):
    """make almanak from date til date"""
    alm = r"""\documentclass[10pt, twoside, a4paper]{report}
    \usepackage[utf8x]{inputenc}
    \usepackage[english]{babel}
    \usepackage{fontenc}
    \usepackage[ top=25mm, bottom=25mm, left=18mm, right=8mm]{geometry}

    \newcommand{\HRule}{\rule{\linewidth}{0.5mm}}
    \usepackage[pdftex]{graphicx}

    \begin{document}

    \begin{titlepage}
     
    \begin{center}
     
    \textsc{\Large Generated by PyAlmanac}\\[1.5cm]

    \includegraphics[width=0.4\textwidth]{./Ra}\\[1cm]

     
    \textsc{\huge The Nautical Almanac for the Sun}\\[0.7cm]
     
    \HRule \\[0.6cm]
    { \Huge \bfseries %s}\\[0.4cm]
     
    \HRule \\[1.5cm]
     
    \begin{center} \large
    \emph{Author:}\\
    Enno \textsc{Rodegerdts}
    \end{center}


     
    \vfill
     
    {\large \today}
    \HRule \\[0.6cm]
    \end{center}
    
    \begin{description}\tiny
    
	\item[Disclaimer:] These are computer generated tables. Use on your own risk. 
    The accuracy has been checked as good as possible but can not be guaranteed. 
    This means, if you get lost on the oceans because of errors in this publication I can not be held liable. 
    For security relevant applications you should buy an official version of the nautical almanac.
	
	\end{description}
     
    \end{titlepage}
    
	DIP corrects for hight of eye over the surface. This value has to be subtracted from the sextant altitude ($H_s$). The  correction in degrees for hight of eye in meters is given by the following formula: 
	\[d=0.0293\sqrt{m}\]
	This is the first correction (apart from index error) that has to be applied to the measured altitude.
	
	The next correction is for refraction in the earths atmosphere. As usual this table is correct for 10°C and a pressure of 1010hPa. This correction has to be applied to apparent altitude ($H_a$). The exact values can be calculated by the following formula.
	\[R_0=\cot \left( H_a + \frac{7.31}{H_a+4.4}\right)\]
	For other than standard conditions calculate a correction factor for $R_0$ by: \[f=\frac{0.28P}{T+273}\] where $P$ is the pressure in hectopascal and $T$ is the temperature in °C.
	
	 Semidiameter has to be added for lower limb sights and subtracted for upper limb sights. The value for semidiameter is tabulated in the daily pages.
	
	To correct your sextant altitude $H_s$ do the following:
	Calculate $H_a$ by
	 \[H_a= H_s+I-dip\] 
	Where $I$ is the sextants index error. Than calculate the observed altitude $H_o$ by
	\[H_o= H_a-R+P\pm SD\]
	where $R$ is refraction, $P$ is parallax and $SD$ is the semidiameter.
	
	Sight reduction tables can be downloaded for the US governments internet pages. Search for HO-229 or HO-249.  These values can also be calculated with to, relatively simple, formulas
	\[ \sin H_c= \sin L \sin d + \cos L \cos d \cos LHA\]
	and
	\[\cos A = \frac{\sin d - \sin L \sin H_c}{\cos L \cos H_c}\]
	where $A$ is the azimuth angle, $L$ is the latitude, $d$ is the declination and $LHA$ is the local hour angle. The azimuth ($Z_n$) is given by the following rule:
	\begin{itemize}
		  \item if the $LHA$ is greater than 180°, $Z_n=A$
		  \item if the $LHA$ is less than 180°, $Z_n = 360° - A$
	\end{itemize}

	\newpage
    """ %(year)
    y = ephem.date(str(year))
    alm = alm + pages(y,25)
    alm = alm + '\end{document}'
    return alm

